kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume5
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/centos/datastore5"


