# =====================================================
#                      _                                          _
#  ___  ___ _ ____   _(_) ___ ___  __ _  ___ ___ ___  _   _ _ __ | |_ ___
# / __|/ _ \ '__\ \ / / |/ __/ _ \/ _` |/ __/ __/ _ \| | | | '_ \| __/ __|
# \__ \  __/ |   \ V /| | (_|  __/ (_| | (_| (_| (_) | |_| | | | | |_\__ \
# |___/\___|_|    \_/ |_|\___\___|\__,_|\___\___\___/ \__,_|_| |_|\__|___/
#                                                          serviceaccounts
# =====================================================
# Service account for accessing secrets API
{{- if .Values.serviceaccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceaccount.name}}

# =====================================================
#       _           _                      _
#   ___| |_   _ ___| |_ ___ _ __ _ __ ___ | | ___  ___
#  / __| | | | / __| __/ _ \ '__| '__/ _ \| |/ _ \/ __|
# | (__| | |_| \__ \ ||  __/ |  | | | (_) | |  __/\__ \
#  \___|_|\__,_|___/\__\___|_|  |_|  \___/|_|\___||___/
#                                          clusterroles
# =====================================================
---
# A role for reading/listing secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{.Values.clusterrole.name}}
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
# =====================================================
#            _      _     _           _ _
#  _ __ ___ | | ___| |__ (_)_ __   __| (_)_ __   __ _ ___
# | '__/ _ \| |/ _ \ '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | | | (_) | |  __/ |_) | | | | | (_| | | | | | (_| \__ \
# |_|  \___/|_|\___|_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                                   rolebindings|___/
# =====================================================
---
# The role binding to combine the  service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.crb.name}}
subjects:
- kind: ServiceAccount
  name: {{.Values.serviceaccount.name}}
  namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Values.clusterrole.name}}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
