apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.virtualservice.name}}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.gateway.name}}
  http:
  - match:
    - uri:
        exact: {{.Values.service.prefix}}
    route:
    - destination:
        host: {{.Values.service.servicename }}
        port:
          number: {{ .Values.service.targetport }}
