---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nodered.fullname" . }}
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi